remove codespell CI job in favor of 1 lint job
merge lint-typo, lint-fix-typo, format, lint-format and lint Makefile
targets into a single `lint` target

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,10 +1,7 @@
 name: Golang Linter
-# Lint runs golangci-lint over the entire CometBFT repository.
+# Lint runs `make lint`
 #
 # This workflow is run on every pull request and push to main.
-#
-# The `golangci` job will pass without running if no *.{go, mod, sum}
-# files have been modified.
 #
 # To run this locally, simply run `make lint` from the root of the repo.
 
@@ -14,25 +11,35 @@ on:
   push:
     branches:
       - main
+
 jobs:
-  golangci:
+  golangci: # preserve old name to avoid changing GH settings
     name: golangci-lint
     runs-on: ubuntu-latest
-    timeout-minutes: 8
+    timeout-minutes: 10
     steps:
       - uses: actions/checkout@v4
+
       - uses: actions/setup-go@v5
         with:
           go-version: '1.21'
-      - uses: technote-space/get-diff-action@v6
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
         with:
-          PATTERNS: |
-            **/**.go
-            go.mod
-            go.sum
-      - uses: golangci/golangci-lint-action@v3
-        with:
-          version: latest
-          args: --timeout 10m
-          github-token: ${{ secrets.github_token }}
-        if: env.GIT_DIFF
+          python-version: '3.x'
+
+        run: |
+          set -euo pipefail
+
+          make lint
+
+          if ! git diff --stat --exit-code ; then
+            echo ">> ERROR:"
+            echo ">>"
+            echo ">> The source code is not linted, not formatted or contains typos."
+            echo ">> Re-run 'make lint' and update this PR."
+            echo ">>"
+            git diff
+            exit 1
+          fi
